CC=gcc
warnings=`cat gcc-4_7_0-release` -Wno-error -Wno-system-headers \
	-Wno-traditional -Wno-traditional-conversion \
	-Wno-c++-compat \
	-Wno-format-nonliteral -Wno-missing-format-attribute -Wno-unused-parameter
debug=$(warnings) -O0 -g
deploy=-w -O3 -s
CFLAGS=$(debug) \
	-ansi -D__STDC_VERSION__=199409L -D_POSIX_C_SOURCE=198809L \
	-I . # These refer to ISO/IEC 9899:1990/Amd 1:1995 and IEEE Std 1003.1-1988.

build: cheat-example

clean:
	$(RM) cheat-example

test: build
	- ./cheat-example -s
	- ./cheat-example -d

cheat-example: cheat.h cheat-helpers.h cheat-example.c
	$(CC) $(CFLAGS) \
		-o cheat-example cheat-example.c

.PHONY: build clean test
