CC=clang
warnings=-Weverything -Wno-error \
	-Wno-covered-switch-default -Wno-disabled-macro-expansion \
	-Wno-conditional-uninitialized -Wno-format-nonliteral -Wno-unused-parameter
debug=$(warnings) -O0 -g
deploy=-w -O3 -s
CFLAGS=$(debug) \
	-ansi -D__STDC_VERSION__=199409L -D_POSIX_C_SOURCE=198809L \
	-I . # These refer to ISO/IEC 9899:1990/Amd 1:1995 and IEEE Std 1003.1-1988.

build: cheat-example

clean:
	$(RM) cheat-example
	$(RM) cheat_captured_*

test: build
	- ./cheat-example

cheat-example: cheat.h cheat-helpers.h cheat-example.c
	$(CC) $(CFLAGS) \
		-o cheat-example cheat-example.c

.PHONY: build clean test
